//! The documentation site: docs/**/*.md -> site/docs/**/*.html, with navigation, search, highlighted
//! PartScript and a "try it" link on every example that opens it in the playground.
//!
//! Two reference pages come from the code, not from hand: the std parts (from std.parts, their comments
//! and parameters) and the material library (from the default host). They are written into docs/ so they
//! read on GitHub too; `docs --check` (and the test suite) checks they are current.

use std::collections::HashSet;
use std::path::Path;

use kitlib::json::Json;
use pulldown_cmark::{html, CowStr, Event, Options, Parser, Tag, TagEnd};
use regex::Regex;

use crate::root;

pub const NAV: [(&str, &[(&str, &str)]); 6] = [
	("Start", &[("index.md", "Overview"), ("start/install.md", "Install and first prop"), ("start/tour.md", "A tour: one lamp, ten ideas"), ("start/tools.md", "Tools: check, build, fmt, preview, playground")]),
	(
		"The language",
		&[
			("language/basics.md", "Basics"),
			("language/shapes.md", "Shapes"),
			("language/materials.md", "Materials and text"),
			("language/copies.md", "Copies"),
			("language/variety.md", "Variety"),
			("language/reuse.md", "Parts made of parts"),
			("language/placing.md", "Placing by name"),
			("language/shaping.md", "Bending and curving"),
			("language/moving.md", "Moving parts"),
		],
	),
	("Places", &[("language/generators.md", "Terrain, ruins, drop and grow"), ("language/paths.md", "Paths, snaps and links"), ("language/buildings.md", "Buildings")]),
	(
		"Guides",
		&[
			("guides/readable.md", "Writing it so it reads well"),
			("guides/psx-style.md", "The PSX look"),
			("guides/cookbook.md", "Cookbook"),
			("guides/gallery.md", "Gallery"),
			("guides/mistakes.md", "Mistakes and what they mean"),
		],
	),
	(
		"Reference",
		&[
			("reference/statements.md", "Every statement and option"),
			("reference/expressions.md", "Expressions"),
			("reference/std-parts.md", "Standard parts"),
			("reference/materials.md", "Material library"),
		],
	),
	("Rust and engines", &[("engine/api.md", "Rust API"), ("engine/hosts.md", "Embedding: hosts and textures"), ("engine/output.md", "What the .glb holds"), ("engine/kitlib.md", "kitlib")]),
];

const KEYWORDS: &[&str] = &[
	"prop", "def", "set", "use", "group", "at", "row", "stack", "if", "part", "size", "card", "snap", "chain", "link", "join", "kit", "building", "room", "open", "walls", "stair", "roof", "attach",
	"place", "wall", "piece", "style", "dressing", "end", "box", "b", "bevel_box", "bb", "box_between", "bx", "cylinder", "c", "cone", "sphere", "sph", "tube", "wedge", "lathe", "extrude", "ext", "pipe",
	"sweep", "face", "panel", "pan", "decal", "trim", "sign", "label", "vault", "arch_wall", "archwall", "torus", "frame", "terrain",
];
const WORDS: &[&str] = &["repeat", "every", "grid", "ring", "step", "scatter", "over", "within", "apart", "on", "facing", "mirror", "as", "for"];

// ------------------------------------------------------------------ generated reference pages

/// docs/reference/std-parts.md from std.parts: every std part, what its comment says, its parameters.
fn std_parts_page() -> String {
	let lines = partscript::lang::splitlines(partscript::project::STD);
	let mut out: Vec<String> = vec![
		"# Standard parts".into(),
		"".into(),
		"<!-- generated by the site tool (crates/site) from crates/partscript/src/std.parts: edit those comments, not this page -->".into(),
		"".into(),
		"Every project can `use` these: building blocks with their origin at the floor centre and their front toward -Y, like a prop. Their materials are parameters (pass `none` to leave a piece out).".into(),
		"".into(),
	];
	let mut k = 0;
	while k < lines.len() {
		let line = lines[k];
		if line.starts_with("def ") {
			let mut comment = Vec::new();
			let mut j = k;
			while j > 0 && lines[j - 1].starts_with('#') {
				comment.insert(0, lines[j - 1].trim_start_matches(['#', ' ']).trim_end().to_string());
				j -= 1;
			}
			let mut header = line.to_string();
			while header.trim_end().ends_with('\\') {
				k += 1;
				let trimmed = header.trim_end();
				header = format!("{} {}", &trimmed[..trimmed.len() - 1], lines[k].trim());
			}
			let words: Vec<&str> = header.split_whitespace().collect();
			let name = words[1];
			let params: Vec<&str> = words[2..].iter().copied().filter(|w| w.contains('=')).collect();
			out.extend([format!("## {name}"), "".into(), comment.join(" "), "".into(), "| parameter | default |".into(), "|---|---|".into()]);
			if params.is_empty() {
				out.push("| (none) | |".into());
			}
			for p in params {
				let (key, default) = p.split_once('=').unwrap();
				out.push(format!("| `{key}` | `{default}` |"));
			}
			out.extend(["".into(), "```parts".into(), format!("prop std_{name}_demo \"{name}\""), format!("  use {name}"), "```".into(), "".into()]);
		}
		k += 1;
	}
	out.join("\n")
}

/// docs/reference/materials.md from the default host's material library.
fn materials_page() -> String {
	use partscript::{BasicProvider, Recipe, TextureProvider};
	let host = partscript::Host::default();
	let library = BasicProvider::default().library();
	let mut out: Vec<String> = vec![
		"# Material library".into(),
		"".into(),
		"<!-- generated by the site tool (crates/site) from the default host (partscript::textures): do not edit -->".into(),
		"".into(),
		"Every project can name these by key (`mat=steel_dark`). A host can add its own; `partscript list` shows what yours knows.".into(),
		"".into(),
		"| key | finish | colour | notes |".into(),
		"|---|---|---|---|".into(),
	];
	let materials = host.materials.borrow();
	let mut keys: Vec<&String> = materials.keys().collect();
	keys.sort();
	for key in keys {
		let Some((_, _, Recipe::Surface { finish, hex })) = library.iter().find(|(k, _, _)| k == key) else { continue };
		let mat = &materials[key];
		let mut notes = Vec::new();
		if !mat.emission.is_empty() || mat.emission_strength > 0.0 {
			notes.push("lit (full bright)".to_string());
		}
		if mat.alpha < 1.0 {
			notes.push(format!("see-through ({})", kitlib::py::g(mat.alpha)));
		}
		out.push(format!("| `{key}` | {finish} | <span class=\"swatch\" style=\"background:#{hex}\"></span> `#{hex}` | {} |", notes.join(", ")));
	}
	let finishes: Vec<String> = partscript::lang::FINISHES.iter().map(|f| format!("`{f}`")).collect();
	out.extend([
		"".into(),
		"## Finishes".into(),
		"".into(),
		format!("Any colour is a material: `#rrggbb/finish`, where the finish is one of {} (paint when left off). `glow` is lit and full bright; `glass` is see-through.", finishes.join(", ")),
		"".into(),
	]);
	out.join("\n")
}

pub fn generated() -> [(&'static str, String); 2] {
	[("reference/std-parts.md", std_parts_page()), ("reference/materials.md", materials_page())]
}

// ------------------------------------------------------------------ highlighting

/// html.escape: & < > " and ' as entities.
pub fn escape(text: &str) -> String {
	let mut out = String::with_capacity(text.len());
	for c in text.chars() {
		match c {
			'&' => out.push_str("&amp;"),
			'<' => out.push_str("&lt;"),
			'>' => out.push_str("&gt;"),
			'"' => out.push_str("&quot;"),
			'\'' => out.push_str("&#x27;"),
			c => out.push(c),
		}
	}
	out
}

/// html.unescape, for the entities the docs produce.
fn unescape(text: &str) -> String {
	let mut out = String::with_capacity(text.len());
	let mut rest = text;
	while let Some(at) = rest.find('&') {
		out.push_str(&rest[..at]);
		rest = &rest[at..];
		let end = rest[1..].find(|c: char| !(c.is_ascii_alphanumeric() || c == '#')).map(|e| e + 1).unwrap_or(rest.len());
		let name = &rest[1..end];
		let decoded = match name {
			"amp" => Some('&'),
			"lt" => Some('<'),
			"gt" => Some('>'),
			"quot" => Some('"'),
			"apos" => Some('\''),
			"nbsp" => Some('\u{a0}'),
			"rarr" => Some('\u{2192}'),
			"larr" => Some('\u{2190}'),
			"middot" => Some('\u{b7}'),
			"mdash" => Some('\u{2014}'),
			"times" => Some('\u{d7}'),
			_ if name.starts_with("#x") => u32::from_str_radix(&name[2..], 16).ok().and_then(char::from_u32),
			_ if name.starts_with('#') => name[1..].parse().ok().and_then(char::from_u32),
			_ => None,
		};
		match decoded {
			Some(c) => {
				out.push(c);
				rest = if rest[end..].starts_with(';') { &rest[end + 1..] } else { &rest[end..] };
			}
			None => {
				out.push('&');
				rest = &rest[1..];
			}
		}
	}
	out.push_str(rest);
	out
}

fn is_word(c: char) -> bool {
	c.is_alphanumeric() || c == '_'
}

fn is_name_start(c: char) -> bool {
	c.is_ascii_lowercase() || c == '_'
}

/// The end of the token at chars[i..] and its kind: comment, string, colour, option, number, word or other
/// (the order a regex alternation tries them in).
fn token(chars: &[char], i: usize) -> (usize, &'static str) {
	let c = chars[i];
	let prev = if i > 0 { Some(chars[i - 1]) } else { None };
	let next = chars.get(i + 1).copied();
	if c == '#' && prev.map_or(true, char::is_whitespace) && next.is_some_and(char::is_whitespace) {
		return (chars.len(), "comment");
	}
	if c == '"' {
		if let Some(close) = chars[i + 1..].iter().position(|&q| q == '"') {
			return (i + close + 2, "string");
		}
	}
	if c == '#' && chars.len() >= i + 7 && chars[i + 1..i + 7].iter().all(char::is_ascii_hexdigit) {
		let mut end = i + 7;
		if chars.get(end) == Some(&'/') && chars.get(end + 1).is_some_and(|&w| is_word(w)) {
			end += 1;
			while chars.get(end).is_some_and(|&w| is_word(w)) {
				end += 1;
			}
		}
		return (end, "colour");
	}
	let boundary = prev.map_or(true, |p| !is_word(p));
	let word_end = || {
		let mut end = i + 1;
		while chars.get(end).is_some_and(|&w| is_word(w)) {
			end += 1;
		}
		end
	};
	if boundary && is_name_start(c) && chars.get(word_end()) == Some(&'=') {
		return (word_end(), "option");
	}
	if prev.map_or(true, |p| !is_word(p) && p != '.') {
		let mut at = i;
		if chars[at] == '-' {
			at += 1;
		}
		if chars.get(at) == Some(&'.') && chars.get(at + 1).is_some_and(char::is_ascii_digit) {
			at += 1;
		}
		if chars.get(at).is_some_and(char::is_ascii_digit) {
			at += 1;
			while chars.get(at).is_some_and(|&d| d.is_ascii_digit() || d == '.') {
				at += 1;
			}
			return (at, "number");
		}
	}
	if boundary && is_name_start(c) {
		return (word_end(), "word");
	}
	(i + 1, "other")
}

pub fn highlight(code: &str) -> String {
	let named = Regex::new(r"^(\s*)([a-z_]\w*)( = )").unwrap();
	let mut out = Vec::new();
	for full in code.split('\n') {
		let mut line = full;
		let mut pieces = String::new();
		if let Some(m) = named.captures(line) {
			pieces.push_str(&format!("{}<span class=\"v\">{}</span>{}", escape(&m[1]), &m[2], &m[3]));
			line = &line[m.get(0).unwrap().end()..];
		}
		let chars: Vec<char> = line.chars().collect();
		let mut first = true;
		let mut i = 0;
		while i < chars.len() {
			let (end, kind) = token(&chars, i);
			let text: String = chars[i..end].iter().collect();
			match kind {
				"word" if first && KEYWORDS.contains(&text.as_str()) => pieces.push_str(&format!("<span class=\"k\">{text}</span>")),
				"word" if WORDS.contains(&text.as_str()) => pieces.push_str(&format!("<span class=\"w\">{text}</span>")),
				"comment" => pieces.push_str(&format!("<span class=\"c\">{}</span>", escape(&text))),
				"string" => pieces.push_str(&format!("<span class=\"s\">{}</span>", escape(&text))),
				"colour" => pieces.push_str(&format!("<span class=\"swatch\" style=\"background:{}\"></span><span class=\"s\">{}</span>", &text[..7], escape(&text))),
				"option" => pieces.push_str(&format!("<span class=\"o\">{text}</span>")),
				"number" => pieces.push_str(&format!("<span class=\"n\">{text}</span>")),
				_ => pieces.push_str(&escape(&text)),
			}
			if !text.chars().all(char::is_whitespace) {
				first = false;
			}
			i = end;
		}
		out.push(pieces);
	}
	out.join("\n")
}

fn runnable(code: &str) -> bool {
	code.split('\n').any(|l| l.starts_with("prop ") || l.starts_with("building "))
}

/// base64.urlsafe_b64encode without its = padding.
fn base64url(bytes: &[u8]) -> String {
	const ALPHABET: &[u8; 64] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_";
	let mut out = String::new();
	for chunk in bytes.chunks(3) {
		let n = chunk.iter().enumerate().fold(0u32, |n, (k, &b)| n | (b as u32) << (16 - 8 * k));
		for k in 0..=chunk.len() {
			out.push(ALPHABET[(n >> (18 - 6 * k) & 63) as usize] as char);
		}
	}
	out
}

// ------------------------------------------------------------------ pages

/// A heading's id as Python-Markdown's toc makes it: ascii, no punctuation, lower case, - between words.
fn slugify(text: &str) -> String {
	let kept: String = text.chars().filter(|c| c.is_ascii() && (c.is_ascii_alphanumeric() || *c == '_' || *c == '-' || c.is_ascii_whitespace())).collect();
	let lower = kept.trim().to_lowercase();
	let mut out = String::new();
	let mut gap = false;
	for c in lower.chars() {
		if c == '-' || c.is_ascii_whitespace() {
			gap = true;
		} else {
			if gap {
				out.push('-');
			}
			gap = false;
			out.push(c);
		}
	}
	if gap {
		out.push('-');
	}
	out
}

fn unique(id: String, ids: &mut HashSet<String>) -> String {
	let mut id = id;
	while id.is_empty() || ids.contains(&id) {
		id = match id.rsplit_once('_') {
			Some((head, n)) if !n.is_empty() && n.chars().all(|c| c.is_ascii_digit()) => format!("{head}_{}", n.parse::<u64>().unwrap() + 1),
			_ => format!("{id}_1"),
		};
	}
	ids.insert(id.clone());
	id
}

/// Markdown to HTML, every heading given an id; also [(id, title)] of its h2 sections.
fn markdown(text: &str) -> (String, Vec<(String, String)>) {
	let events: Vec<Event> = Parser::new_ext(text, Options::ENABLE_TABLES).collect();
	let mut ids = HashSet::new();
	let mut sections = Vec::new();
	let mut out: Vec<Event> = Vec::with_capacity(events.len());
	let mut k = 0;
	while k < events.len() {
		if let Event::Start(Tag::Heading { level, id: None, classes, attrs }) = &events[k] {
			let end = k + events[k..].iter().position(|e| matches!(e, Event::End(TagEnd::Heading(_)))).unwrap();
			let name: String = events[k + 1..end]
				.iter()
				.filter_map(|e| match e {
					Event::Text(t) | Event::Code(t) => Some(t.to_string()),
					_ => None,
				})
				.collect();
			let id = unique(slugify(&name), &mut ids);
			if *level == pulldown_cmark::HeadingLevel::H2 {
				sections.push((id.clone(), name));
			}
			out.push(Event::Start(Tag::Heading { level: *level, id: Some(CowStr::from(id)), classes: classes.clone(), attrs: attrs.clone() }));
			k += 1;
			continue;
		}
		out.push(events[k].clone());
		k += 1;
	}
	let mut body = String::new();
	html::push_html(&mut body, out.into_iter());
	(body, sections)
}

/// (html body, [(id, title)] of its sections, search entries) of one page.
fn render(path: &str, text: &str, depth: usize, title: &str) -> (String, Vec<(String, String)>, Vec<Json>) {
	let fence = Regex::new(r"(?ms)^```([^\n]*)\n(.*?)^```\s*$").unwrap();
	let mut blocks: Vec<(String, String)> = Vec::new();
	let text = fence.replace_all(text, |m: &regex::Captures| {
		let (lang, code) = (m[1].trim(), &m[2]);
		let key = format!("CODEBLOCK{}X", blocks.len());
		let block = if lang.starts_with("parts") {
			let body = highlight(code.trim_end_matches('\n'));
			let mut button = String::new();
			if runnable(code) {
				button = format!("<a class=\"try\" href=\"{}play.html#code={}\" title=\"open this in the playground\">try it</a>", "../".repeat(depth + 1), base64url(code.as_bytes()));
			}
			format!("<div class=\"code parts\">{button}<pre>{body}</pre></div>")
		} else {
			format!("<div class=\"code\"><pre>{}</pre></div>", escape(code.trim_end_matches('\n')))
		};
		blocks.push((key.clone(), block));
		format!("\n\n{key}\n\n")
	});
	let (mut body, sections) = markdown(&text);
	for (key, value) in &blocks {
		body = body.replace(&format!("<p>{key}</p>"), value);
	}
	let code = Regex::new(r"<code>(.*?)</code>").unwrap();
	body = code.replace_all(&body, |m: &regex::Captures| format!("<code>{}</code>", m[1].replace("\\|", "|"))).into_owned();
	// Links between pages: .md in the sources, .html on the site.
	let link = Regex::new(r##"href="([^"#:]+)\.md(#[^"]*)?""##).unwrap();
	body = link.replace_all(&body, |m: &regex::Captures| format!("href=\"{}.html{}\"", &m[1], m.get(2).map_or("", |g| g.as_str()))).into_owned();
	let heading = Regex::new(r#"<h2 id="([^"]+)">(.*?)</h2>"#).unwrap();
	let noise = Regex::new(r#"<a class="try"[^>]*>.*?</a>|</?span[^>]*>"#).unwrap();
	let tag = Regex::new(r"<[^>]+>").unwrap();
	let space = Regex::new(r"\s+").unwrap();
	let mut cuts: Vec<usize> = body.match_indices("<h2 ").map(|(at, _)| at).collect();
	cuts.insert(0, 0);
	cuts.push(body.len());
	let mut entries = Vec::new();
	for pair in cuts.windows(2) {
		let part = &body[pair[0]..pair[1]];
		if pair[0] == pair[1] && pair[1] != 0 {
			continue;
		}
		let found = heading.captures(part);
		let part = noise.replace_all(part, "");
		let plain = unescape(&tag.replace_all(&part, " "));
		let text: String = space.replace_all(&plain, " ").chars().take(1200).collect();
		let mut entry = Json::dict();
		entry
			.set("page", path.replace(".md", ".html"))
			.set("anchor", found.as_ref().map_or(String::new(), |h| h[1].to_string()))
			.set("title", title)
			.set("section", found.as_ref().map_or(String::new(), |h| unescape(&tag.replace_all(&h[2], ""))))
			.set("text", text);
		entries.push(entry);
	}
	(body, sections, entries)
}

const TEMPLATE: &str = r#"<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title} · PartScript</title>
<link rel="stylesheet" href="{up}docs.css">
<link rel="icon" href="{up}../icon.svg" type="image/svg+xml">
<script src="{up}../theme.js"></script>
</head>
<body class="app">
<div class="chrome">
	<div class="titlebar"><img class="icon" src="{up}../icon.svg" alt=""><span class="title">{title} · PartScript Help</span>
		<span class="controls"><a class="ctl" href="{up}../index.html" title="Close: back to the home page" aria-label="Close">×</a></span></div>
	<nav class="menubar"><a href="{up}index.html">Contents</a><a href="{up}../play.html">Playground</a><a href="{up}../viewer.html">Models</a>
		<a href="{up}../index.html">Home</a><a href="https://github.com/meowers-dev/partscript">GitHub</a>
		<span class="right"><button class="theme" type="button">Dark mode</button><label for="search">Search:</label><input id="search" type="search" placeholder="press /" autocomplete="off"></span></nav>
</div>
<div id="results" hidden></div>
<div class="layout">
<aside class="nav">{nav}</aside>
<main>
{body}
<div class="pager">{pager}</div>
</main>
<aside class="toc">{toc}</aside>
</div>
<script>window.DOCS_UP = "{up}";</script>
<script src="{up}search.js"></script>
</body>
</html>
"#;

/// The template with each {name} replaced (only in the template, never inside what goes in).
fn fill(template: &str, values: &[(&str, &str)]) -> String {
	let mut out = String::new();
	let mut rest = template;
	while let Some(at) = rest.find('{') {
		out.push_str(&rest[..at]);
		let close = rest[at..].find('}').map(|c| at + c);
		match close.and_then(|c| values.iter().find(|(k, _)| *k == &rest[at + 1..c]).map(|(_, v)| (c, v))) {
			Some((c, v)) => {
				out.push_str(v);
				rest = &rest[c + 1..];
			}
			None => {
				out.push('{');
				rest = &rest[at + 1..];
			}
		}
	}
	out.push_str(rest);
	out
}

fn nav_html(current: &str, up: &str) -> String {
	let mut out = String::new();
	for (group, pages) in NAV {
		out.push_str(&format!("<h4>{group}</h4><ul>"));
		for (path, title) in pages {
			let on = if *path == current { " class=\"on\"" } else { "" };
			out.push_str(&format!("<li><a{on} href=\"{up}{}\">{title}</a></li>", path.replace(".md", ".html")));
		}
		out.push_str("</ul>");
	}
	out
}

fn io<T>(result: std::io::Result<T>, path: &Path) -> Result<T, String> {
	result.map_err(|e| format!("{}: {e}", path.display()))
}

/// The generated pages that differ from what is in docs/.
pub fn stale() -> Vec<(&'static str, String)> {
	let docs = root().join("docs");
	generated().into_iter().filter(|(path, fresh)| std::fs::read_to_string(docs.join(path)).ok().as_deref() != Some(fresh.as_str())).collect()
}

/// Pages in NAV with no source.
pub fn missing() -> Vec<&'static str> {
	let docs = root().join("docs");
	NAV.iter().flat_map(|(_, pages)| pages.iter().map(|(p, _)| *p)).filter(|p| !docs.join(p).exists()).collect()
}

pub fn build(check_only: bool) -> Result<(), String> {
	let docs = root().join("docs");
	let out_dir = root().join("site/docs");
	let stale = stale();
	if check_only {
		if !stale.is_empty() {
			return Err(format!("out of date (run cargo run -p site -- docs): {}", stale.iter().map(|(p, _)| *p).collect::<Vec<_>>().join(", ")));
		}
		println!("generated reference pages are current");
		return Ok(());
	}
	for (path, fresh) in &stale {
		let target = docs.join(path);
		io(std::fs::create_dir_all(target.parent().unwrap()), &target)?;
		io(std::fs::write(&target, fresh), &target)?;
	}
	let missing = missing();
	if !missing.is_empty() {
		return Err(format!("pages in NAV with no source: {}", missing.join(", ")));
	}
	let order: Vec<(&str, &str)> = NAV.iter().flat_map(|(_, pages)| pages.iter().copied()).collect();
	let mut index = Vec::new();
	for (k, (path, title)) in order.iter().enumerate() {
		let depth = path.matches('/').count();
		let up = "../".repeat(depth);
		let source = docs.join(path);
		let (body, sections, entries) = render(path, &io(std::fs::read_to_string(&source), &source)?, depth, title);
		index.extend(entries);
		let toc = if sections.is_empty() {
			String::new()
		} else {
			format!("<h4>On this page</h4><ul>{}</ul>", sections.iter().map(|(i, t)| format!("<li><a href=\"#{i}\">{}</a></li>", escape(t))).collect::<String>())
		};
		let mut pager = String::new();
		if k > 0 {
			let (p, t) = order[k - 1];
			pager += &format!("<a class=\"prev\" href=\"{up}{}\">&larr; {t}</a>", p.replace(".md", ".html"));
		}
		if k + 1 < order.len() {
			let (p, t) = order[k + 1];
			pager += &format!("<a class=\"next\" href=\"{up}{}\">{t} &rarr;</a>", p.replace(".md", ".html"));
		}
		let page = fill(TEMPLATE, &[("title", &escape(title)), ("up", &up), ("nav", &nav_html(path, &up)), ("body", &body), ("toc", &toc), ("pager", &pager)]);
		let target = out_dir.join(path.replace(".md", ".html"));
		io(std::fs::create_dir_all(target.parent().unwrap()), &target)?;
		io(std::fs::write(&target, page), &target)?;
	}
	for asset in ["docs.css", "search.js"] {
		let from = root().join("site/docs-assets").join(asset);
		io(std::fs::copy(&from, out_dir.join(asset)), &from)?;
	}
	let images = docs.join("img");
	if images.exists() {
		io(std::fs::create_dir_all(out_dir.join("img")), &images)?;
		for image in io(std::fs::read_dir(&images), &images)? {
			let image = image.map_err(|e| e.to_string())?.path();
			io(std::fs::copy(&image, out_dir.join("img").join(image.file_name().unwrap())), &image)?;
		}
	}
	let search = out_dir.join("search.json");
	io(std::fs::write(&search, Json::List(index).dumps(false)), &search)?;
	home()?;
	let refreshed = if stale.is_empty() { String::new() } else { format!(" (refreshed {})", stale.iter().map(|(p, _)| *p).collect::<Vec<_>>().join(", ")) };
	println!("{} pages -> {}{refreshed}", order.len(), out_dir.display());
	Ok(())
}

/// site/index.html, the home page, from its template: the writer's desk source highlighted in.
fn home() -> Result<(), String> {
	let path = root().join("examples/layout.parts");
	let source = io(std::fs::read_to_string(&path), &path)?;
	let start = source.find("prop writers_desk").ok_or("examples/layout.parts has no writers_desk")?;
	let lines = partscript::lang::splitlines(&source[start..]);
	let end = (1..lines.len()).find(|&k| lines[k].chars().next().is_some_and(|c| !c.is_whitespace())).unwrap_or(lines.len());
	let desk = lines[..end].join("\n");
	let code = format!("<div class=\"code parts\"><pre>{}</pre></div>", highlight(desk.trim_end()));
	let template = root().join("site/docs-assets/home.html");
	let page = io(std::fs::read_to_string(&template), &template)?.replace("{desk_code}", &code);
	let target = root().join("site/index.html");
	io(std::fs::write(&target, page), &target)
}

#[cfg(test)]
mod tests {
	use super::*;

	#[test]
	fn base64_matches_python() {
		assert_eq!(base64url(b"prop a"), "cHJvcCBh");
		assert_eq!(base64url(b"prop ab"), "cHJvcCBhYg");
		assert_eq!(base64url(b"\xff\xfe"), "__4");
	}

	#[test]
	fn slugs_match_python_markdown() {
		assert_eq!(slugify("Materials: kitlib.geom.Mat"), "materials-kitlibgeommat");
		assert_eq!(slugify("check()"), "check");
		assert_eq!(slugify("cylinder, cone"), "cylinder-cone");
		let mut ids = HashSet::new();
		assert_eq!(unique("a".into(), &mut ids), "a");
		assert_eq!(unique("a".into(), &mut ids), "a_1");
		assert_eq!(unique("a".into(), &mut ids), "a_2");
	}

	#[test]
	fn generated_pages_are_current() {
		assert!(stale().is_empty(), "out of date (run cargo run -p site -- docs): {:?}", stale().iter().map(|(p, _)| *p).collect::<Vec<_>>());
	}

	#[test]
	fn every_page_is_in_the_nav() {
		assert!(missing().is_empty(), "pages in NAV with no source: {:?}", missing());
		let listed: HashSet<&str> = NAV.iter().flat_map(|(_, pages)| pages.iter().map(|(p, _)| *p)).collect();
		let docs = root().join("docs");
		let mut on_disk = Vec::new();
		let mut todo = vec![docs.clone()];
		while let Some(dir) = todo.pop() {
			for entry in std::fs::read_dir(dir).unwrap() {
				let path = entry.unwrap().path();
				if path.is_dir() {
					todo.push(path);
				} else if path.extension().is_some_and(|e| e == "md") {
					on_disk.push(path.strip_prefix(&docs).unwrap().to_string_lossy().to_string());
				}
			}
		}
		let unlisted: Vec<&String> = on_disk.iter().filter(|p| !listed.contains(p.as_str())).collect();
		assert!(unlisted.is_empty(), "pages missing from NAV: {unlisted:?}");
	}
}
