"""Builds the documentation site: docs/**/*.md -> site/docs/**/*.html, with navigation, search,
highlighted PartScript and a "try it" link on every example that opens it in the playground.

	uv run python site/docs.py            # write site/docs/ (and refresh the generated reference pages)
	uv run python site/docs.py --check    # fail if a generated reference page is out of date

Two reference pages come from the code, not from hand: the std parts (from std.parts, their comments
and parameters) and the material library (from the default host). They are written into docs/ so they
read on GitHub too; the test suite checks they are current.
"""

from __future__ import annotations

import base64
import html
import json
import re
import sys
from pathlib import Path

import markdown

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
OUT = ROOT / "site" / "docs"

NAV = [
	("Start", [("index.md", "Overview"), ("start/install.md", "Install and first prop"), ("start/tour.md", "A tour: one lamp, ten ideas"),
		("start/tools.md", "Tools: check, build, fmt, preview, playground")]),
	("The language", [("language/basics.md", "Basics"), ("language/shapes.md", "Shapes"), ("language/materials.md", "Materials and text"),
		("language/copies.md", "Copies"), ("language/variety.md", "Variety"), ("language/reuse.md", "Parts made of parts"),
		("language/placing.md", "Placing by name"), ("language/shaping.md", "Bending and curving")]),
	("Places", [("language/generators.md", "Terrain, ruins, drop and grow"), ("language/paths.md", "Paths, snaps and links"),
		("language/buildings.md", "Buildings")]),
	("Guides", [("guides/readable.md", "Writing it so it reads well"), ("guides/psx-style.md", "The PSX look"), ("guides/cookbook.md", "Cookbook"), ("guides/gallery.md", "Gallery"),
		("guides/mistakes.md", "Mistakes and what they mean")]),
	("Reference", [("reference/statements.md", "Every statement and option"), ("reference/expressions.md", "Expressions"),
		("reference/std-parts.md", "Standard parts"), ("reference/materials.md", "Material library")]),
	("Python and engines", [("python/api.md", "Python API"), ("python/hosts.md", "Embedding: hosts and textures"),
		("python/output.md", "What the .glb holds"), ("python/kitlib.md", "kitlib")]),
]

KEYWORDS = {"prop", "def", "set", "use", "group", "at", "row", "stack", "if", "part", "size", "card", "snap", "chain", "link", "join",
	"kit", "building", "room", "open", "walls", "stair", "roof", "attach", "place", "wall", "piece", "style", "dressing", "end",
	"box", "b", "bevel_box", "bb", "box_between", "bx", "cylinder", "c", "cone", "sphere", "sph", "tube", "wedge", "lathe", "extrude", "ext",
	"pipe", "sweep", "face", "panel", "pan", "decal", "trim", "sign", "label", "vault", "arch_wall", "archwall", "torus", "frame", "terrain"}
WORDS = {"repeat", "every", "grid", "ring", "step", "scatter", "over", "within", "apart", "on", "facing", "mirror", "as", "for"}


# ------------------------------------------------------------------ generated reference pages
def std_parts_page() -> str:
	"""docs/reference/std-parts.md from std.parts: every std part, what its comment says, its parameters."""
	from partscript.project import STD
	text = STD.read_text()
	lines = text.splitlines()
	out = ["# Standard parts", "", "<!-- generated by site/docs.py from src/partscript/std.parts: edit those comments, not this page -->", "",
		"Every project can `use` these: building blocks with their origin at the floor centre and their front toward -Y, "
		"like a prop. Their materials are parameters (pass `none` to leave a piece out).", ""]
	k = 0
	while k < len(lines):
		line = lines[k]
		if line.startswith("def "):
			comment = []
			j = k - 1
			while j >= 0 and lines[j].startswith("#"):
				comment.insert(0, lines[j].lstrip("# ").rstrip())
				j -= 1
			header = line
			while header.rstrip().endswith("\\"):
				k += 1
				header = header.rstrip()[:-1] + " " + lines[k].strip()
			words = header.split()
			name, params = words[1], [w for w in words[2:] if "=" in w]
			out += [f"## {name}", "", " ".join(comment), "", "| parameter | default |", "|---|---|"]
			out += [f"| `{p.split('=', 1)[0]}` | `{p.split('=', 1)[1]}` |" for p in params] or ["| (none) | |"]
			out += ["", "```parts", f'prop std_{name}_demo "{name}"', f"  use {name}", "```", ""]
		k += 1
	return "\n".join(out)


def materials_page() -> str:
	"""docs/reference/materials.md from the default host's material library."""
	from partscript import Host
	from partscript.lang import FINISHES
	from partscript.textures import _LIBRARY
	host = Host()
	out = ["# Material library", "", "<!-- generated by site/docs.py from the default host (partscript.textures): do not edit -->", "",
		"Every project can name these by key (`mat=steel_dark`). A host can add its own; `partscript list` shows what yours knows.", "",
		"| key | finish | colour | notes |", "|---|---|---|---|"]
	for key in sorted(host.materials):
		finish, colour, opts = _LIBRARY[key]
		mat = host.materials[key]
		notes = []
		if mat.emission or mat.emission_strength > 0:
			notes.append("lit (full bright)")
		if mat.alpha < 1:
			notes.append(f"see-through ({mat.alpha:g})")
		out.append(f'| `{key}` | {finish} | <span class="swatch" style="background:#{colour}"></span> `#{colour}` | {", ".join(notes)} |')
	out += ["", "## Finishes", "", "Any colour is a material: `#rrggbb/finish`, where the finish is one of "
		+ ", ".join(f"`{f}`" for f in FINISHES) + " (paint when left off). `glow` is lit and full bright; `glass` is see-through.", ""]
	return "\n".join(out)


GENERATED = {"reference/std-parts.md": std_parts_page, "reference/materials.md": materials_page}


# ------------------------------------------------------------------ highlighting
_TOKEN = re.compile(r'(?P<comment>(?:^|(?<=\s))#\s.*$)|(?P<string>"[^"]*")|(?P<colour>#[0-9a-fA-F]{6}(?:/\w+)?)|(?P<option>\b[a-z_]\w*(?==))'
	r"|(?P<number>(?<![\w.])-?\.?\d[\d.]*)|(?P<word>\b[a-z_]\w*\b)|(?P<other>.)", re.M)


def highlight(code: str) -> str:
	out = []
	for line in code.split("\n"):
		first = True
		named = re.match(r"^(\s*)([a-z_]\w*)( = )", line)
		pieces = []
		if named:
			pieces.append(html.escape(named.group(1)) + f'<span class="v">{named.group(2)}</span>{named.group(3)}')
			line = line[named.end():]
		for m in _TOKEN.finditer(line):
			kind, text = m.lastgroup, m.group()
			if kind == "word" and first and text in KEYWORDS:
				pieces.append(f'<span class="k">{text}</span>')
			elif kind == "word" and text in WORDS:
				pieces.append(f'<span class="w">{text}</span>')
			elif kind == "comment":
				pieces.append(f'<span class="c">{html.escape(text)}</span>')
			elif kind == "string":
				pieces.append(f'<span class="s">{html.escape(text)}</span>')
			elif kind == "colour":
				pieces.append(f'<span class="swatch" style="background:{text[:7]}"></span><span class="s">{html.escape(text)}</span>')
			elif kind == "option":
				pieces.append(f'<span class="o">{text}</span>')
			elif kind == "number":
				pieces.append(f'<span class="n">{text}</span>')
			else:
				pieces.append(html.escape(text))
			if not text.isspace():
				first = False
		out.append("".join(pieces))
	return "\n".join(out)


def runnable(code: str) -> bool:
	return bool(re.search(r"^(prop|building) ", code, re.M))


# ------------------------------------------------------------------ pages
def render(path: str, text: str, depth: int, title: str = "") -> tuple[str, list, list]:
	"""(html body, [(id, title)] of its sections, search entries) of one page."""
	blocks: dict = {}

	def stash(match) -> str:
		lang, code = match.group(1).strip(), match.group(2)
		key = f"CODEBLOCK{len(blocks)}X"
		if lang.startswith("parts"):
			body = highlight(code.rstrip("\n"))
			button = ""
			if runnable(code):
				encoded = base64.urlsafe_b64encode(code.encode()).decode().rstrip("=")
				button = f'<a class="try" href="{"../" * (depth + 1)}play.html#code={encoded}" title="open this in the playground">try it</a>'
			blocks[key] = f'<div class="code parts">{button}<pre>{body}</pre></div>'
		else:
			blocks[key] = f'<div class="code"><pre>{html.escape(code.rstrip(chr(10)))}</pre></div>'
		return f"\n\n{key}\n\n"

	text = re.sub(r"^```([^\n]*)\n(.*?)^```\s*$", stash, text, flags=re.S | re.M)
	md = markdown.Markdown(extensions=["tables", "toc", "attr_list"], extension_configs={"toc": {"toc_depth": "2-3"}})
	body = md.convert(text)
	for key, value in blocks.items():
		body = body.replace(f"<p>{key}</p>", value)
	body = re.sub(r"<code>(.*?)</code>", lambda m: "<code>" + m.group(1).replace("\\|", "|") + "</code>", body)  # a | escaped for a table
	# Links between pages: .md in the sources, .html on the site.
	body = re.sub(r'href="([^"#:]+)\.md(#[^"]*)?"', lambda m: f'href="{m.group(1)}.html{m.group(2) or ""}"', body)
	sections = [(t["id"], t["name"]) for t in _flat(md.toc_tokens) if t["level"] == 2]
	entries = []
	title = title or path
	for part in re.split(r"(?=<h2 )", body):
		heading = re.search(r'<h2 id="([^"]+)">(.*?)</h2>', part)
		part = re.sub(r'<a class="try"[^>]*>.*?</a>|</?span[^>]*>', "", part)
		plain = html.unescape(re.sub(r"<[^>]+>", " ", part))
		entries.append({"page": path.replace(".md", ".html"), "anchor": heading.group(1) if heading else "",
			"title": title, "section": html.unescape(re.sub(r"<[^>]+>", "", heading.group(2))) if heading else "",
			"text": re.sub(r"\s+", " ", plain)[:1200]})
	return body, sections, entries


def _flat(tokens: list) -> list:
	out = []
	for token in tokens:
		out.append(token)
		out += _flat(token.get("children", []))
	return out


TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title} · PartScript</title>
<link rel="stylesheet" href="{up}docs.css">
<link rel="icon" href="{up}../icon.svg" type="image/svg+xml">
</head>
<body>
<header>
	<a class="brand" href="{up}index.html">PARTSCRIPT</a>
	<input id="search" type="search" placeholder="search the docs" autocomplete="off">
	<nav class="top"><a href="{up}../play.html">playground</a><a href="{up}../viewer.html">models</a><a href="{up}../index.html">home</a>
	<a href="https://github.com/meowers-dev/partscript">github</a></nav>
</header>
<div id="results" hidden></div>
<div class="layout">
<aside class="nav">{nav}</aside>
<main>
{body}
<div class="pager">{pager}</div>
</main>
<aside class="toc">{toc}</aside>
</div>
<script>window.DOCS_UP = "{up}";</script>
<script src="{up}search.js"></script>
</body>
</html>
"""


def nav_html(current: str, up: str) -> str:
	out = []
	for group, pages in NAV:
		out.append(f"<h4>{group}</h4><ul>")
		for path, title in pages:
			on = ' class="on"' if path == current else ""
			out.append(f'<li><a{on} href="{up}{path.replace(".md", ".html")}">{title}</a></li>')
		out.append("</ul>")
	return "".join(out)


def build(check_only: bool = False) -> None:
	stale = []
	for path, make in GENERATED.items():
		target = DOCS / path
		fresh = make()
		if not target.exists() or target.read_text() != fresh:
			stale.append(path)
			if not check_only:
				target.parent.mkdir(parents=True, exist_ok=True)
				target.write_text(fresh)
	if check_only:
		if stale:
			sys.exit(f"out of date (run uv run python site/docs.py): {', '.join(stale)}")
		print("generated reference pages are current")
		return
	order = [path for _, pages in NAV for path, _ in pages]
	missing = [p for p in order if not (DOCS / p).exists()]
	if missing:
		sys.exit(f"pages in NAV with no source: {', '.join(missing)}")
	OUT.mkdir(parents=True, exist_ok=True)
	index = []
	titles = {path: title for _, pages in NAV for path, title in pages}
	for k, path in enumerate(order):
		depth = path.count("/")
		up = "../" * depth
		body, sections, entries = render(path, (DOCS / path).read_text(), depth, titles[path])
		index += entries
		toc = "<h4>On this page</h4><ul>" + "".join(f'<li><a href="#{i}">{html.escape(t)}</a></li>' for i, t in sections) + "</ul>" if sections else ""
		pager = ""
		if k > 0:
			pager += f'<a class="prev" href="{up}{order[k - 1].replace(".md", ".html")}">&larr; {titles[order[k - 1]]}</a>'
		if k + 1 < len(order):
			pager += f'<a class="next" href="{up}{order[k + 1].replace(".md", ".html")}">{titles[order[k + 1]]} &rarr;</a>'
		page = TEMPLATE.format(title=html.escape(titles[path]), up=up, nav=nav_html(path, up), body=body, toc=toc, pager=pager)
		target = OUT / path.replace(".md", ".html")
		target.parent.mkdir(parents=True, exist_ok=True)
		target.write_text(page)
	for asset in ("docs.css", "search.js"):
		(OUT / asset).write_text((ROOT / "site" / "docs-assets" / asset).read_text())
	images = DOCS / "img"
	if images.exists():
		(OUT / "img").mkdir(exist_ok=True)
		for image in images.iterdir():
			(OUT / "img" / image.name).write_bytes(image.read_bytes())
	(OUT / "search.json").write_text(json.dumps(index))
	home()
	print(f"{len(order)} pages -> {OUT}" + (f" (refreshed {', '.join(stale)})" if stale else ""))


def home() -> None:
	"""site/index.html, the home page, from its template: the writer's desk source highlighted in."""
	source = (ROOT / "examples" / "layout.parts").read_text()
	lines = source[source.index("prop writers_desk"):].splitlines()
	end = next((k for k, line in enumerate(lines[1:], 1) if line and not line[0].isspace()), len(lines))
	desk = "\n".join(lines[:end]).rstrip()
	code = f'<div class="code parts"><pre>{highlight(desk)}</pre></div>'
	(ROOT / "site" / "index.html").write_text((ROOT / "site" / "docs-assets" / "home.html").read_text().replace("{desk_code}", code))


if __name__ == "__main__":
	build(check_only="--check" in sys.argv)
